import type { Product } from '@/types';

export const products: Product[] = [
  {
    id: 1,
    name: 'Kente Cloth Scarf',
    price: 45.00,
    description: 'A vibrant, handwoven Kente cloth scarf from Ghana, featuring traditional patterns and rich colors. Made from 100% cotton, it is a versatile accessory for any occasion.',
    image: 'https://placehold.co/600x600.png',
    category: 'clothing',
    currency: 'USD',
  },
  {
    id: 2,
    name: 'Beaded Maasai Necklace',
    price: 75.00,
    description: 'An intricate, handmade necklace crafted by Maasai artisans in Kenya. This statement piece features colorful glass beads arranged in traditional geometric patterns.',
    image: 'https://placehold.co/600x600.png',
    category: 'accessories',
    currency: 'USD',
  },
  {
    id: 3,
    name: 'Hand-carved Wooden Mask',
    price: 120.00,
    description: 'A stunning decorative mask, hand-carved from a single piece of ebony wood by Makonde craftsmen in Tanzania. It represents a cultural story and adds a touch of African heritage to any space.',
    image: 'https://placehold.co/600x600.png',
    category: 'crafts',
    currency: 'USD',
  },
  {
    id: 4,
    name: 'Ankara Print Dress',
    price: 95.00,
    description: 'A beautiful and bold dress made from authentic Ankara wax print fabric from Nigeria. This modern silhouette is perfect for summer events and celebrations.',
    image: 'https://placehold.co/600x600.png',
    category: 'clothing',
    currency: 'USD',
  },
  {
    id: 5,
    name: 'Woven Bolga Basket',
    price: 60.00,
    description: 'A durable and stylish market basket, handwoven from elephant grass by artisans in Bolgatanga, Ghana. Features a leather-wrapped handle for comfort and longevity.',
    image: 'https://placehold.co/600x600.png',
    category: 'crafts',
    currency: 'USD',
  },
  {
    id: 6,
    name: 'Brass Adinkra Earrings',
    price: 35.00,
    description: 'Elegant earrings featuring the "Gye Nyame" Adinkra symbol, which means "except for God," signifying the supremacy of God. Cast in brass by Ghanaian artisans.',
    image: 'https://placehold.co/600x600.png',
    category: 'accessories',
    currency: 'USD',
  },
  {
    id: 7,
    name: 'Mudcloth Throw Blanket',
    price: 150.00,
    description: 'An authentic Bogolanfini, or mudcloth, throw from Mali. This textile is traditionally hand-dyed with fermented mud and plant dyes, creating unique symbolic patterns.',
    image: 'https://placehold.co/600x600.png',
    category: 'crafts',
    currency: 'USD',
  },
  {
    id: 8,
    name: 'Leather Berber Backpack',
    price: 180.00,
    description: 'A handcrafted leather backpack from Morocco, featuring traditional Berber patterns and kilim fabric accents. Spacious and durable for daily use or travel.',
    image: 'https://placehold.co/600x600.png',
    category: 'accessories',
    currency: 'USD',
  },
];
